export const API_RES_MSG_COMMON = {
    DELETE_SUCCESS: 'es {{value}} has been successfully deleted',
    DELETE_FAILED: 'es Failed to delete {{value}}',
    SEARCH_RESULT_FOUND: 'es Search {{value}} has been success',
    SEARCH_RESULT_NOT_FOUND: 'es Search result not found',
    DATA_NOT_FOUND: 'es Data not found',
    FAILED_TO_CREATE: 'es Failed to create {{value}}',
    FAILED_TO_UPDATE: 'es Failed to update {{value}}',
    ALREADY_CREATED: 'es This {{value}} is already created',
    ENABLE_SUCCESS: 'es {{value}} has been successfully enabled',
    PASSWORD_HAS_BEEN_UPDATED: 'es Password has been updated',
    LINK_HAS_BEEN_EXPIRED: 'es Link has been expired, please request new link',
    LINK_IS_NOT_VALID: 'es Link is not valid, please request valid link',
    SOMETHING_WENT_WRONG: 'es Something went wrong',
    EROR_WHILE_ADDING_DATA: 'es Eror while adding data',
    UNABLE_TO_FETCH_SELECTED_RECORD: 'es Unable to fetch selected Record',
    UNABLE_TO_FIND_RECORD: 'es Unable to find Record',
    PLEASE_ENTER_VALID_URL_TO_CONTINUE: 'es Please enter valid url to continue',
    DELETE_FAILED_COMMON: 'es Delete failed',
    DATA_UPDATED_SUCCESSFULLY: 'es Data Updated Successfully',
    BAD_REQUEST: 'es Bad Request',
    ERROR_WHILE_FETCHING_RECORD: 'es Error While Fetching Record',
    ERROR_WHILE_CREATING_RECORD: 'es Error While Creating Record',
    ERROR_WHILE_UPDATING_RECORD: 'es Error While Updating Record',
    THE_RECAPTCHA_WAS_INVALID: 'es The reCAPTCHA was invalid. Please try it again.',
    COPPIED_SUCCESSFULLY: 'es Copied successfully'
};
