export const API_RES_MSG_USER = {
    PLEASE_VERIFY_THAT_YOU_ARE_A_HUMAN: 'es Please verify that you are a human',
    USER_EMAIL_HAS_ALREADY_BEEN_REGISTERED: 'es User already registered with {{value}}',
    COMPANYNAME_HAS_ALREADY_BEEN_REGISTERED: 'es {{value}} has already been registered',
    FAILED_TO_GENERATE_RANDOM_PASSWORD_PLEASE_TRY_AGAIN: 'es Failed to generate random password, Please try again',
    USER_NOT_FOUND: 'es User not found',
    NOT_A_ADMIN_USER: 'es Not a admin user',
    GENERATED_PASSWORD_FAILED_TO_SAVE: 'es Generated password failed to save',
    PASSWORD_FAILED_TO_SAVE: 'es Password failed to save',
    COMPANY_ID_NOT_FOUND: 'es Company id not found',
    BAD_REQUEST: 'es Bad request',
    SAME_PASSWORD: 'es Same password',
    YOUR_NEW_PASSWORD_IS_SAME_AS_CURRENT_PASSWORD: 'es Your new password is same as current password',
    INCORRECT_PASSWORD: 'es You have entered incorrect password',
    LINK_EXPIRED: 'es Link has been expired, please request new link.',
    RESET_PASSWORD_LINK_ERROR: 'es Reset password link error',
    EMAIL_NOT_FOUND: 'es Email not found.Wrong email or password',
    WRONG_EMAIL_OR_PASSWORD: 'es Wrong email or password',
    WRONG_EMAIL_OR_PASSWORD_ATTEMPT: 'es Wrong email or password, you have {{value}} attempt left',
    INACTIVE_ACCOUNT: 'es Your account is not active',
    USER_HAS_BEEN_BLOCKED_ATTEMPT: 'es You have been blocked for too many failed attempts, please try to login again after {{value}}',
    USER_CANNOT_BE_DELETED: 'es User can not be deleted',
    USER_HAS_SURVEY_RECORD_AND_USER_CANNOT_BE_DISABLED: 'es User has survey record, so user can not be disabled',
    USER_DELETED: 'es User has been successfully deleted',
    TRANSFER_TOKEN_EXIPRED_OR_INVALID: 'es Transfer token expired or invalid',
    UNABLE_TO_VERIFY_USER: 'es Unable to verify user',
    YOUR_ACCOUNT_IS_NOT_ACTIVE: 'es Your account is not active',
    SUBSCRIPTION_TYPE_ALREADY_EXISTS: 'es Subscription type already exists',
    NEW_COMPANY_ADDED: 'es Successfully added a user.',
    NEW_USER_ADDED: 'es Successfully added a user.',
    USER_CREATION_FAILED: 'es Failed to add a user',
    USER_UPDATED: 'es Successfully updated a user',
    USER_UPDATE_FAILED: 'es Failed to update a user',
    USER_VERIFIED: 'es Successfully verified a user',
    SUCCESSFULLY_ADDED_SKILLS: 'es Successfully added skills',
    FAILED_TO_ADD_SKILLS: 'es Failed to add skills',
    SUCCESSFULLY_ADDED_LANGUAGES: 'es Successfully added languages',
    FAILED_TO_ADD_LANGUAGES: 'es Failed to add languages',
    USER_ALREADY_EXIST_WITH_THOSE_STAFFING: 'es User already exist with those staffings',
    USER_ENABLED: 'es User has been successfully enabled',
    USER_DISABLED: 'es User has been successfully disabled',
    USER_ALREADY_ENABLED: 'es User is already enabled',
    FAILED_TO_ENABLE_USER: 'es Failed to enable user',
    SUBSCRIPTION_UPDATED: 'es Successfully updated subscription type of user',
    RELATED_COMPANY_NOT_FOUND: 'es Invalid Login. You are not associated with any company',
    PASSWORD_CHANGED_SUCCESSFULLY: 'es Password has been changed successfully',
    FAILED_TO_CHANGE_PASSWORD: 'es Failed to change password',
    PERSONAL_DETAILS_UPDATED_SUCCESSFULLY: 'es Personal Details Updated Successfully',
    SUCCESSFULLY_REMOVED_FROM_LANGUAGES: 'es Successfully removed from languages',
    SUCCESSFULLY_REMOVED_FROM_SKILLS: 'es Successfully removed from skills',
    CAN_NOT_ADD_COMPANY_ADMIN_AS_COMPANY_USER: 'es Can not add company admin as company user',
    CAN_NOT_ADD_YOURSELF_AS_COMPANY_USER: 'es Sorry, you do not have permission to change your access, please contact company admin or super-admin',
    FAILED_TO_REJECT: 'es Failed to reject company',
    FAILED_TO_SAVE_REJECTION_INFORMATION: 'es Failed to save rejected information',
    SUCCESSFULLY_FETCHED_REJECTION_INFORMATION_OF_USER: 'es Successfully fetched rejected information of the organization',
    FAILED_TO_REJECT_ORGANIZATION: 'es Failed to reject organization',
    REJECTED_USER_ID_IS_REQUIRED_IN_USER_REJECT_INFORMATION_SCHEMA: 'es Rejected user is required',
    REJECTED_ORGANIZATION_ID_IS_REQUIRED_IN_USER_REJECT_INFORMATION_SCHEMA: 'Organization is required in organization reject information',
    REJECTED_BY_USERID_IS_REQUIRED_IN_USER_REJECT_INFORMATION_SCHEMA: 'es The user who reject the organization is required',
    REJECTED_USER: 'es Successfully rejected organization',
    FAILED_TO_REMOVE_REJECT_FLAG: 'es Failed to allow organization for verification',
    REMOVED_REJECT_FLAG: 'es Allowed organization for verification',
    FAILED_TO_UPDATE_REJECTION_INFORMATION: 'es Failed to update rejected inforamtion of organization',
    SUCCESSFULLY_UPDATED_REJECTION_INFORMATION_OF_USER: 'es Successfully updated rejected information of organization',
    USER_UNBLOCKED_SUCCESSFULLY: 'es Successfully unblocked user',
    FAILED_TO_UNBLOCK_USER: 'es Failed to unblock user',
    CANNOT_DISABLE_ADMIN: 'es Sorry, admin user cannot be disabled.',
    USER_HAS_BEEN_LOGGED_OUT: 'es User has been logged out',
    LOGOUT_SUCCESS: 'es Logout success'
};
