export const API_RES_MSG_BLOCKCHAIN = {
    BC_NODE_INFO_ALREADY_EXISTS: 'This BC Node Info Is Already Exist',
    BC_NODE_INFO_ADD_FAILED: 'Unable To Add BC Node Info',
    BC_NODE_INFO_ADDED: 'New BC Node Info Added Successfully',
    INCORRECT_BC_NODE_INFO: 'Incorrect Bc Node Info',
    BC_NODE_INFO_NOT_FOUND: 'Bc Node Info Not Found',
    FETCHED_ALL_BC_NODE_INFO: 'Fetched All Bc Node Info',
    BC_NODE_INFO_UPDATE_FAILED: 'Unable To Updated BC Node Info',
    BC_NODE_INFO_UPDATED: 'BC Node Info Updated Successfully',
    BC_NODE_INFO_DELETE_FAILED: 'Unable To Delete BC Node Info',
    BC_NODE_INFO_DELETED: ' BC Node Info Deleted Successfully',
    SUCCESSFULLY_ADDED_CHANNEL_DETAIL: 'New Channel Details Added Successfully',
    SUCCESSFULLY_UPDATED_CHANNEL_DETAIL: 'Channel Details Updated Successfully',
    SUCCESSFULLY_DELETED_CHANNEL_DETAIL: 'Channel Deleted Successfully',
    FETCHED_ALL_CHANNEL_DETAIL: 'All Channel Fetched',
    CHANNEL_DETAIL_ALREADY_EXISTS: 'This Channel details already Exists',
    CHANNEL_ID_NOT_FOUND: 'Channel Id Not Found',
    INVALID_BC_KEY: 'Invalid Bc Key',
    UNABLE_TO_DELETE_BC_NODE_INFO: 'Unable to disable BC Node. Already assigned on staffing.',
    BC_NODE_INFO_ENABLED_SUCCESS: 'Bc Node Info Enabled Successfully',
    UNABLE_TO_ENABLE_BC_NODE_INFO: 'Unable To Enable Bc Node Info'
};
