export const API_RES_MSG_COMMON = {
    DELETE_SUCCESS: '{{value}} has been successfully deleted',
    DELETE_FAILED: 'Failed to delete {{value}}',
    SEARCH_RESULT_FOUND: 'Search {{value}} has been success',
    SEARCH_RESULT_NOT_FOUND: 'Search result not found',
    DATA_NOT_FOUND: 'Data not found',
    FAILED_TO_CREATE: 'Failed to create {{value}}',
    FAILED_TO_UPDATE: 'Failed to update {{value}}',
    ALREADY_CREATED: 'This {{value}} is already created',
    ENABLE_SUCCESS: '{{value}} has been successfully enabled',
    PASSWORD_HAS_BEEN_UPDATED: 'Password has been updated',
    LINK_HAS_BEEN_EXPIRED: 'Link has been expired, please request new link',
    LINK_IS_NOT_VALID: 'Link is not valid, please request valid link',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    EROR_WHILE_ADDING_DATA: 'Eror while adding data',
    UNABLE_TO_FETCH_SELECTED_RECORD: 'Unable to fetch selected Record',
    UNABLE_TO_FIND_RECORD: 'Unable to find Record',
    PLEASE_ENTER_VALID_URL_TO_CONTINUE: 'Please enter valid url to continue',
    DELETE_FAILED_COMMON: 'Delete failed',
    DATA_UPDATED_SUCCESSFULLY: 'Data Updated Successfully',
    BAD_REQUEST: 'Bad Request',
    ERROR_WHILE_FETCHING_RECORD: 'Error While Fetching Record',
    ERROR_WHILE_CREATING_RECORD: 'Error While Creating Record',
    ERROR_WHILE_UPDATING_RECORD: 'Error While Updating Record',
    THE_RECAPTCHA_WAS_INVALID: 'The reCAPTCHA was invalid. Please try it again.',
    COPPIED_SUCCESSFULLY: 'Copied successfully',
    TOKEN_EXPIRED_LOGOUT: 'The session has been expired. Please re-login to continue'
};
