export const API_RES_MSG_MANAGE_PROJECT = {
    PROJECT_ALREADY_EXIST: 'This Project Is Already Exist',
    UNABLE_TO_CREATE_PROJECT: 'Unable To Create Project',
    NEW_PROJECT_CREATED: 'New Project Created Successfully',
    UNABLE_TO_DELETE_PROJECT: 'Unable To Disable The Project',
    PROJECT_DELETED_SUCCESS: 'Project Disabled Successfully',
    UNABLE_TO_ENABLE_PROJECT: 'Unable To Enable The Project',
    PROJECT_ENABLED_SUCCESS: 'Project Enabled Successfully',
    UNABLE_TO_UPDATE_PROJECT: 'Unable To Update Project',
    PROJECT_RECORD_UPDATED: 'Project Updated Successfully',
    PROJECT_VERSION_ALREADY_EXITS: 'This Version Is Already Exist',
    UNABLE_TO_ADD_VERSION: 'Unable To Add Version',
    NEW_VERSION_ADDED_SUCCESS: 'New Version Added Successfully',
    UNABLE_TO_ADD_MONITORING_REPORT: 'Unable To Add Monitoring Report',
    MONITORING_REPORT_ADDED_SUCCESS: 'New Report Added Successfully',
    REVIEW_MODEL_ADDED_SUCCESS: 'Review Model Added Successfully',
    UNABLE_TO_ADD_REVIEW_MODEL: 'Unable To add Review Model',
    UNABLE_TO_ADD_MODEL_REVIEW: 'Unable To add Model Review Status',
    NEW_REVIEW_ADD_SUCCESS: 'Model Review Status Added Successfully'
};
