export const API_RES_MSG_USER = {
    PLEASE_VERIFY_THAT_YOU_ARE_A_HUMAN: 'Please verify that you are a human',
    USER_EMAIL_HAS_ALREADY_BEEN_REGISTERED: 'User already registered with {{value}}',
    COMPANYNAME_HAS_ALREADY_BEEN_REGISTERED: '{{value}} has already been registered',
    FAILED_TO_GENERATE_RANDOM_PASSWORD_PLEASE_TRY_AGAIN: 'Failed to generate random password, Please try again',
    USER_NOT_FOUND: 'User not found',
    NOT_A_ADMIN_USER: 'Not a admin user',
    GENERATED_PASSWORD_FAILED_TO_SAVE: 'Generated password failed to save',
    PASSWORD_FAILED_TO_SAVE: 'Password failed to save',
    COMPANY_ID_NOT_FOUND: 'Company id not found',
    BAD_REQUEST: 'Bad request',
    SAME_PASSWORD: 'Same password',
    YOUR_NEW_PASSWORD_IS_SAME_AS_CURRENT_PASSWORD: 'Your new password is same as current password',
    INCORRECT_PASSWORD: 'You have entered incorrect password',
    LINK_EXPIRED: 'Link has been expired, please request new link.',
    RESET_PASSWORD_LINK_ERROR: 'Reset password link error',
    EMAIL_NOT_FOUND: 'Email not found.Wrong email or password',
    WRONG_EMAIL_OR_PASSWORD: 'Wrong email or password',
    WRONG_EMAIL_OR_PASSWORD_ATTEMPT: 'Wrong email or password, you have {{value}} attempt left',
    INACTIVE_ACCOUNT: 'Your account is not active',
    USER_HAS_BEEN_BLOCKED_ATTEMPT: 'You have been blocked for too many failed attempts, please try to login again after {{value}}',
    USER_CANNOT_BE_DELETED: 'User can not be deleted',
    USER_HAS_SURVEY_RECORD_AND_USER_CANNOT_BE_DISABLED: 'User has survey record, so user can not be disabled',
    USER_DELETED: 'User has been successfully deleted',
    TRANSFER_TOKEN_EXIPRED_OR_INVALID: 'Transfer token expired or invalid',
    UNABLE_TO_VERIFY_USER: 'Unable to verify user',
    YOUR_ACCOUNT_IS_NOT_ACTIVE: 'Your account is not active',
    SUBSCRIPTION_TYPE_ALREADY_EXISTS: 'Subscription type already exists',
    NEW_COMPANY_ADDED: 'Successfully added a user.',
    NEW_USER_ADDED: 'Successfully added a user.',
    USER_CREATION_FAILED: 'Failed to add a user',
    USER_UPDATED: 'Successfully updated a user',
    USER_UPDATE_FAILED: 'Failed to update a user',
    USER_VERIFIED: 'Successfully verified a user',
    SUCCESSFULLY_ADDED_SKILLS: 'Successfully added skills',
    FAILED_TO_ADD_SKILLS: 'Failed to add skills',
    SUCCESSFULLY_ADDED_LANGUAGES: 'Successfully added languages',
    FAILED_TO_ADD_LANGUAGES: 'Failed to add languages',
    USER_ALREADY_EXIST_WITH_THOSE_STAFFING: 'User already exist with those staffings',
    USER_ENABLED: 'User has been successfully enabled',
    USER_DISABLED: 'User has been successfully disabled',
    USER_ALREADY_ENABLED: 'User is already enabled',
    FAILED_TO_ENABLE_USER: 'Failed to enable user',
    SUBSCRIPTION_UPDATED: 'Successfully updated subscription type of user',
    RELATED_COMPANY_NOT_FOUND: 'Invalid Login. You are not associated with any company',
    PASSWORD_CHANGED_SUCCESSFULLY: 'Password has been changed successfully',
    FAILED_TO_CHANGE_PASSWORD: 'Failed to change password',
    PERSONAL_DETAILS_UPDATED_SUCCESSFULLY: 'Personal Details Updated Successfully',
    SUCCESSFULLY_REMOVED_FROM_LANGUAGES: 'Successfully removed from languages',
    SUCCESSFULLY_REMOVED_FROM_SKILLS: 'Successfully removed from skills',
    CAN_NOT_ADD_COMPANY_ADMIN_AS_COMPANY_USER: 'Can not add company admin as company user',
    CAN_NOT_ADD_YOURSELF_AS_COMPANY_USER: 'Sorry, you do not have permission to change your access, please contact company admin or super-admin',
    FAILED_TO_REJECT: 'Failed to reject company',
    FAILED_TO_SAVE_REJECTION_INFORMATION: 'Failed to save rejected information',
    SUCCESSFULLY_FETCHED_REJECTION_INFORMATION_OF_USER: 'Successfully fetched rejected information of the organization',
    FAILED_TO_REJECT_ORGANIZATION: 'Failed to reject organization',
    REJECTED_USER_ID_IS_REQUIRED_IN_USER_REJECT_INFORMATION_SCHEMA: 'Rejected user is required',
    REJECTED_ORGANIZATION_ID_IS_REQUIRED_IN_USER_REJECT_INFORMATION_SCHEMA: 'Organization is required in organization reject information',
    REJECTED_BY_USERID_IS_REQUIRED_IN_USER_REJECT_INFORMATION_SCHEMA: 'The user who reject the organization is required',
    REJECTED_USER: 'Successfully rejected organization',
    FAILED_TO_REMOVE_REJECT_FLAG: 'Failed to allow organization for verification',
    REMOVED_REJECT_FLAG: 'Allowed organization for verification',
    FAILED_TO_UPDATE_REJECTION_INFORMATION: 'Failed to update rejected inforamtion of organization',
    SUCCESSFULLY_UPDATED_REJECTION_INFORMATION_OF_USER: 'Successfully updated rejected information of organization',
    USER_UNBLOCKED_SUCCESSFULLY: 'Successfully unblocked user',
    FAILED_TO_UNBLOCK_USER: 'Failed to unblock user',
    CANNOT_DISABLE_ADMIN: 'Sorry, admin user cannot be disabled.',
    USER_HAS_BEEN_LOGGED_OUT: 'User has been logged out',
    LOGOUT_SUCCESS: 'Logout success',
    YOU_DONT_HAVE_ACCESS_TO_MANAGE_BLOCKED_COMPANY_USERS: `You don't have access to manage blocked company users`,
    YOU_CANT_UNBLOCK_THIS_USER: `You can't unblock this user`,
    SUCCESSFULLY_UNBLOCKED_COMPANY_USER: 'Successfully unblocked company user',
    FAILED_TO_UNBLOCK_COMPANY_USER: 'Failed to unblock company user'
};
