export const MSG_KEY_CONSTANT_COMMON = {
    DELETE_FAILED: 'DELETE_FAILED',
    PASSWORD_HAS_BEEN_UPDATED: 'PASSWORD_HAS_BEEN_UPDATED',
    LINK_HAS_BEEN_EXPIRED: 'LINK_HAS_BEEN_EXPIRED',
    LINK_IS_NOT_VALID: 'LINK_IS_NOT_VALID',
    SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
    EROR_WHILE_ADDING_DATA: 'EROR_WHILE_ADDING_DATA',
    UNABLE_TO_FETCH_SELECTED_RECORD: 'UNABLE_TO_FETCH_SELECTED_RECORD',
    UNABLE_TO_FIND_RECORD: 'UNABLE_TO_FIND_RECORD',
    PLEASE_ENTER_VALID_URL_TO_CONTINUE: 'PLEASE_ENTER_VALID_URL_TO_CONTINUE',
    DELETE_FAILED_COMMON: 'DELETE_FAILED_COMMON',
    DATA_UPDATED_SUCCESSFULLY: 'DATA_UPDATED_SUCCESSFULLY',
    BAD_REQUEST: 'BAD_REQUEST',
    ERROR_WHILE_FETCHING_RECORD: 'ERROR_WHILE_FETCHING_RECORD',
    ERROR_WHILE_CREATING_RECORD: 'ERROR_WHILE_CREATING_RECORD',
    ERROR_WHILE_UPDATING_RECORD: 'ERROR_WHILE_UPDATING_RECORD',
    THE_RECAPTCHA_WAS_INVALID: 'THE_RECAPTCHA_WAS_INVALID',
    COPPIED_SUCCESSFULLY: 'COPPIED_SUCCESSFULLY'
};
