export const MSG_KEY_CONSTANT_ORGANIZATION = {
    ORGANIZATIONS_NOT_FOUND: 'ORGANIZATIONS_NOT_FOUND',
    ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
    SUCCESSFULLY_UPDATED_ORGANIZATION: 'Successfully updated organization',
    COMPANY_NAME_IS_REQUIRED_FOR_THE_SURVEYOR: 'COMPANY_NAME_IS_REQUIRED_FOR_THE_SURVEYOR',
    DATA_ADDED_SUCCESSFULLY: 'DATA_ADDED_SUCCESSFULLY'
};
