export const MSG_KEY_CONSTANT_USER = {
    USER_DELETED: 'USER_DELETED',
    NEW_USER_ADDED: 'NEW_USER_ADDED',
    USER_CREATION_FAILED: 'USER_CREATION_FAILED',
    USER_UPDATED: 'USER_UPDATED',
    USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
    USER_VERIFIED: 'USER_VERIFIED',
    FAILED_TO_CHANGE_PASSWORD: 'FAILED_TO_CHANGE_PASSWORD',
    PERSONAL_DETAILS_UPDATED_SUCCESSFULLY: 'PERSONAL_DETAILS_UPDATED_SUCCESSFULLY',
    SUCCESSFULLY_REMOVED_FROM_LANGUAGES: 'SUCCESSFULLY_REMOVED_FROM_LANGUAGES',
    SUCCESSFULLY_REMOVED_FROM_SKILLS: 'SUCCESSFULLY_REMOVED_FROM_SKILLS'
};
